// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypzuaazojbnliaacscpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwenVhYXpvamJubGlhYWNzY3B3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzkzMjksImV4cCI6MjA2OTkxNTMyOX0.l1SnanchlW6tDf56YJAGpFCqs6unlRmmj1ZaUCwzNJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});